export const ACTIVITY_REQUEST = "ACTIVITY_REQUEST";
export const ACTIVITY_CREATE_SUCCESS = "ACTIVITY_CREATE_SUCCESS";
export const ACTIVITY_ERROR = "ACTIVITY_ERROR";
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
export const GET_ONE = "GET_ONE";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const GET_WAIT_MEMBERS_SUCCESS = "GET_WAIT_MEMBERS_SUCCESS"; 